## Import Library

In [ ]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, recall_score

## Load dataset

In [ ]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


## Data preprocessing

### Label Encoding

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


**Cara 1**

In [ ]:
le = preprocessing.LabelEncoder()
le.fit(df['embark_town'])
df['embark_town_label_encoding'] = le.transform(df['embark_town'])

In [ ]:
Embarked_Label_Encoding = df[['embark_town','embark_town_label_encoding',]]
Embarked_Label_Encoding.head()

,embark_town,embark_town_label_encoding
0,Southampton,2
1,Cherbourg,0
2,Southampton,2
3,Southampton,2
4,Southampton,2


**Cara 2**

In [ ]:
df['embark_town_label_cat'] = df['embark_town'].astype('category').cat.codes

In [ ]:
embark_town_label_cat = df[['embark_town','embark_town_label_encoding','embark_town_label_cat']]
embark_town_label_cat.head()

,embark_town,embark_town_label_encoding,embark_town_label_cat
0,Southampton,2,2
1,Cherbourg,0,0
2,Southampton,2,2
3,Southampton,2,2
4,Southampton,2,2


In [ ]:
embark_town_label_cat.drop_duplicates()

,embark_town,embark_town_label_encoding,embark_town_label_cat
0,Southampton,2,2
1,Cherbourg,0,0
5,Queenstown,1,1
61,NaN,3,-1


### Ordinal Encoding

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
map_class = {'First':3,
             'Second':2,
             'Third':1}
df['class_cat'] = df['class'].map(map_class)
df[['class','class_cat']].head()

,class,class_cat
0,Third,1
1,First,3
2,Third,1
3,First,3
4,Third,1


In [ ]:
df[['class','class_cat']].drop_duplicates()

,class,class_cat
0,Third,1
1,First,3
9,Second,2


### One Hot Encoding

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
dummies_embark_town = pd.get_dummies(df['embark_town'],prefix='embark_town')
dummies_embark_town.head()

,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
0,0,0,1
1,1,0,0
2,0,0,1
3,0,0,1
4,0,0,1


In [ ]:
df = pd.concat([df, dummies_embark_town], axis=1)
df[['embark_town','embark_town_Cherbourg','embark_town_Queenstown','embark_town_Southampton']].head()

,embark_town,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
0,Southampton,0,0,1
1,Cherbourg,1,0,0
2,Southampton,0,0,1
3,Southampton,0,0,1
4,Southampton,0,0,1


### Frequency Encoding

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
freq_et = df['embark_town'].value_counts().reset_index()
freq_et.rename(columns={"index": "embark_town", "embark_town": "freq_embark_town"}, inplace = True)
freq_et['pct_embark_town'] = round((freq_et['freq_embark_town']/freq_et['freq_embark_town'].sum())*100,2)
freq_et

,embark_town,freq_embark_town,pct_embark_town
0,Southampton,644,72.44
1,Cherbourg,168,18.90
2,Queenstown,77,8.66


In [ ]:
df = df.merge(freq_et[['embark_town','pct_embark_town']], on='embark_town', how='inner')
df[['embark_town','pct_embark_town']]

,embark_town,pct_embark_town
0,Southampton,72.44
1,Southampton,72.44
2,Southampton,72.44
3,Southampton,72.44
4,Southampton,72.44
...,...,...
884,Queenstown,8.66
885,Queenstown,8.66
886,Queenstown,8.66
887,Queenstown,8.66


### Mean Encoding

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


**Hitung kemunculan category pada dataset**

In [ ]:
freq_et= df['embark_town'].value_counts().reset_index()
freq_et.rename(columns={"index": "embark_town", "embark_town": "freq_embark_town"}, inplace = True)
freq_et

,embark_town,freq_embark_town
0,Southampton,644
1,Cherbourg,168
2,Queenstown,77


**Jumlahkan value target(survived) berdasarkan category**

In [ ]:
sum_et = df.groupby(['embark_town']).agg({'survived':sum}).reset_index()
sum_et.rename(columns={"survived": "sum_embark_town"}, inplace = True)
sum_et

,embark_town,sum_embark_town
0,Cherbourg,93
1,Queenstown,30
2,Southampton,217


**Hitung mean encoding untuk embark_town**

In [ ]:
mean_ec = freq_et.merge(sum_et, on='embark_town', how='inner')
mean_ec['mean_ec_embark_town'] = round((mean_ec['sum_embark_town']/mean_ec['freq_embark_town']),2)
mean_ec

,embark_town,freq_embark_town,sum_embark_town,mean_ec_embark_town
0,Southampton,644,217,0.34
1,Cherbourg,168,93,0.55
2,Queenstown,77,30,0.39


In [ ]:
df = df.merge(mean_ec[['embark_town','mean_ec_embark_town']], on='embark_town', how='inner')
df[['embark_town','mean_ec_embark_town']]

,embark_town,mean_ec_embark_town
0,Southampton,0.34
1,Southampton,0.34
2,Southampton,0.34
3,Southampton,0.34
4,Southampton,0.34
...,...,...
884,Queenstown,0.39
885,Queenstown,0.39
886,Queenstown,0.39
887,Queenstown,0.39


## Imbalanced Data handling

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [ ]:
target = df['survived'].value_counts().reset_index()
target.rename(columns={'index':'survived','survived':'freq'}, inplace=True)
target['percentage'] = round((target['freq']/target['freq'].sum())*100,2)
target

,survived,freq,percentage
0,0,549,61.62
1,1,342,38.38


In [ ]:
df_numeric = df[['survived','pclass','age','sibsp','parch','fare']]
df_numeric = df_numeric.dropna()
df_numeric.head()

,survived,pclass,age,sibsp,parch,fare
0,0,3,22.0,1,0,7.2500
1,1,1,38.0,1,0,71.2833
2,1,3,26.0,0,0,7.9250
3,1,1,35.0,1,0,53.1000
4,0,3,35.0,0,0,8.0500


In [ ]:
df_numeric['survived'].value_counts()

0    424
1    290
Name: survived, dtype: int64

In [ ]:
from imblearn import under_sampling, over_sampling

X = df_numeric.drop(['survived'],axis=1)
y = df_numeric['survived']

# Undersampling
X_under, y_under = under_sampling.RandomUnderSampler().fit_resample(X, y)


In [ ]:
df_undersampling = pd.concat([X_under, y_under], axis=1)
df_undersampling.head(3)

,pclass,age,sibsp,parch,fare,survived
0,3,40.5,0,0,7.75,0
1,2,54.0,0,0,26.00,0
2,2,32.0,2,0,73.50,0


In [ ]:
df_undersampling['survived'].value_counts()

1    290
0    290
Name: survived, dtype: int64

## Random Forest with Imbalance data

### Load Dataset

In [ ]:
df = sns.load_dataset('titanic')
df = df.dropna().reset_index(drop=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
1,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
2,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
3,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
4,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True


### Data Preprocessing

In [ ]:
# df =pd.get_dummies(data=df,columns=['embarked','sex', 'class', 'who',
#                                       'adult_male','deck','embark_town',
#                                       'alive','alone'],drop_first=True)

df = df[['survived','pclass','age','sibsp','parch','fare']]
df.head()

,survived,pclass,age,sibsp,parch,fare
0,1,1,38.0,1,0,71.2833
1,1,1,35.0,1,0,53.1000
2,0,1,54.0,0,0,51.8625
3,1,3,4.0,1,1,16.7000
4,1,1,58.0,0,0,26.5500


In [ ]:
df['survived'].value_counts()

1    123
0     59
Name: survived, dtype: int64

### Split Dataset

In [ ]:
X = df.drop(['survived'],axis = 1)
Y = df['survived']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

# 75% train
# 25% test

In [ ]:
X_train.head()

,pclass,age,sibsp,parch,fare
117,1,39.0,1,1,110.8833
38,1,38.0,1,0,90.0000
118,1,36.0,0,0,40.1250
150,1,27.0,1,0,53.1000
75,1,25.0,1,0,55.4417


### Modeling denga Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
preds = model.predict(X_test)

In [ ]:
preds

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1], dtype=int64)

### Metric Evaluation

Karena sudah tidak balanced data, jadi TIDAK valid menggunakan akurasi<br><br>

gunakan AUC atau F1 score

In [ ]:
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, recall_score

In [ ]:
cm = confusion_matrix(y_test, preds)
cm

array([[ 8, 10],
       [ 3, 25]], dtype=int64)

In [ ]:
# y_test = actual
# preds = prediksi

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score, recall_score

In [ ]:
# calculate AUC
from sklearn.metrics import roc_auc_score
print('AUC ',roc_auc_score(y_test, preds))

AUC  0.6686507936507936


In [ ]:
# 97% tepat, error 3%

In [ ]:
# 100 prediksi akan ada 3 org yg gagal/slh prediksi

In [ ]:
# calculate F1 Score
from sklearn.metrics import f1_score
print('F1 Score ',f1_score(y_test, preds))


F1 Score  0.7936507936507937


Bagaimana mencari Precision dan Recall?

In [ ]:
# calculate Precision
from sklearn.metrics import precision_score
print('Precision ',precision_score(y_test, preds))


Precision  0.7142857142857143


In [ ]:
# calculate Recall
from sklearn.metrics import recall_score
print('Recall ',recall_score(y_test, preds))


Recall  0.8928571428571429


In [ ]:
X_train.head()

,pclass,age,sibsp,parch,fare
117,1,39.0,1,1,110.8833
38,1,38.0,1,0,90.0000
118,1,36.0,0,0,40.1250
150,1,27.0,1,0,53.1000
75,1,25.0,1,0,55.4417


In [ ]:
new_passenger = pd.DataFrame({
    'pclass':[1],
    'age':[30],
    'sibsp':[0],
    'parch':[1],
    'fare': [100]
})

new_passenger

,pclass,age,sibsp,parch,fare
0,1,30,0,1,100


In [ ]:
new_passenger_preds = model.predict(new_passenger)
new_passenger_preds

array([1], dtype=int64)

In [ ]:
user trx -> model -> respon 1 fraud/ 0 non fraud