In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# load data
admit = pd.read_csv('/content/drive/MyDrive/Bimbing/Regularized Regression in Python/regression_data.csv')
admit.head()

,gre_score,toefl_score,univ_ranking,motiv_letter_strength,recommendation_strength,gpa,research_exp,admit_prob
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65


In [15]:
# split train test
from sklearn.model_selection import train_test_split

feature = admit.drop(columns='admit_prob')
target = admit[['admit_prob']]

feature_admit_train, feature_admit_test, target_admit_train, target_admit_test = train_test_split(feature, target, test_size=0.20, random_state=42)

In [7]:
X = admit.drop(columns='admit_prob')
y = admit[['admit_prob']]

X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.20, random_state=42)

In [8]:
# calculate VIF scores
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif
from statsmodels.tools.tools import add_constant

X = add_constant(feature_admit_train)

vif_df = pd.DataFrame([vif(X.values, i)
               for i in range(X.shape[1])],
              index=X.columns).reset_index()
vif_df.columns = ['feature','vif_score']
vif_df = vif_df.loc[vif_df.feature!='const']
vif_df

,feature,vif_score
1,gre_score,4.489983
2,toefl_score,3.664298
3,univ_ranking,2.572110
4,motiv_letter_strength,2.785764
5,recommendation_strength,1.977698
6,gpa,4.654540
7,research_exp,1.518065


In [9]:
# drop redundant features
feature_admit_train = feature_admit_train.drop(columns=['gre_score','toefl_score'])
feature_admit_test = feature_admit_test.drop(columns=['gre_score','toefl_score'])

# one hot encoding = Drop first = True

In [10]:
# feature_admit_train['new_feat'] = (feature_admit_train['gre_score'] + feature_admit_train['toefl_score'] + feature_admit_train['gpa']/3)

# bagus mana dari setiap asumi?? jawabannya di evaluasi

In [17]:
y_admit_train = target_admit_train.to_numpy()
y_admit_train.shape

(400, 1)

In [18]:
y_admit_train = y_admit_train.reshape(len(y_admit_train),)
y_admit_train.shape

(400,)

In [19]:
from sklearn.linear_model import Ridge, Lasso

# train the model
X_admit_train = feature_admit_train.to_numpy()
y_admit_train = target_admit_train.to_numpy()
y_admit_train = y_admit_train.reshape(len(y_admit_train),)

In [20]:
# define the model
ridge_reg = Ridge(alpha=0.1,
                  random_state=42)

ridge_reg.fit(X_admit_train, y_admit_train)

# b0, b1, b2, dst..

Ridge(alpha=0.1, random_state=42)

In [22]:
# ridge_reg = RAM

# ridge_reg -> save .pkl
# music -> .mp3
# video -> .mp4

In [33]:
y_pred_ridge = ridge_reg.predict(feature_admit_test)
y_pred_ridge

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but Ridge was fitted without feature names
  warnings.warn(


array([0.91448237, 0.79505506, 0.57287923, 0.70729354, 0.81581046,
       0.86202971, 0.47453498, 0.64839147, 0.82358439, 0.8073962 ,
       0.72199634, 0.725844  , 0.65649856, 0.93682038, 0.82398544,
       0.50969439, 0.83938153, 0.59714869, 0.53332652, 0.57160192,
       0.66549545, 0.55311442, 0.72224438, 0.79509734, 0.78031215,
       0.60237729, 0.94837585, 0.84741197, 0.62782637, 0.74341742,
       0.55537692, 0.72998667, 0.5448077 , 0.86108356, 0.65727247,
       0.73719059, 0.55411679, 0.95715374, 0.64363885, 0.71055561,
       0.97031003, 0.57491421, 0.67066879, 0.85832131, 0.94108605,
       0.57780577, 0.95834683, 0.83904996, 0.79598812, 0.92566861,
       0.88793755, 0.56367874, 0.70357352, 0.52669773, 0.95366342,
       0.5977676 , 0.955864  , 0.73914629, 0.66243327, 0.5012883 ,
       0.62926108, 0.68022112, 0.59888538, 0.59222926, 0.44084773,
       0.58891466, 0.86669528, 0.89782025, 0.6582746 , 0.70660584,
       0.61763472, 0.78590451, 0.69144439, 0.5628886 , 0.55414

In [ ]:
# fakta nya adalah 0.93 dan prediksi adalah 0.91448237
# maka residual = 0.93  - 0.91448237

In [29]:
target_admit_test.values[0:5]

array([[0.93],
       [0.84],
       [0.39],
       [0.77],
       [0.74]])

In [30]:
data = feature_admit_train
model = ridge_reg

coef_df = pd.DataFrame({
    'feature':['intercept'] + data.columns.tolist(),
    'coefficient':[model.intercept_] + list(model.coef_)
})

coef_df

,feature,coefficient
0,intercept,-1.422332
1,gre_score,0.002443
2,toefl_score,0.003004
3,univ_ranking,0.002589
4,motiv_letter_strength,0.001850
5,recommendation_strength,0.017263
6,gpa,0.112172
7,research_exp,0.023991


In [ ]:
# MHS, UTS, QUIZ, UTS, ABSENSI, UANG JAJAN, LULUS ??

In [31]:
lasso_reg = Lasso(alpha=0.1,
                  random_state=42)

lasso_reg.fit(X_admit_train, y_admit_train)

Lasso(alpha=0.1, random_state=42)

In [32]:
data = feature_admit_train
model = lasso_reg

coef_df = pd.DataFrame({
    'feature':['intercept'] + data.columns.tolist(),
    'coefficient':[model.intercept_] + list(model.coef_)
})

coef_df

,feature,coefficient
0,intercept,-2.204020
1,gre_score,0.007962
2,toefl_score,0.003786
3,univ_ranking,0.000000
4,motiv_letter_strength,0.000000
5,recommendation_strength,0.000000
6,gpa,0.000000
7,research_exp,0.000000


In [34]:
y_pred_losso = lasso_reg.predict(feature_admit_test)
y_pred_losso

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but Lasso was fitted without feature names
  warnings.warn(


array([0.89450728, 0.70497641, 0.70157965, 0.69283859, 0.81566592,
       0.83576577, 0.48359738, 0.59389738, 0.74061082, 0.76789369,
       0.77663475, 0.72468675, 0.74974139, 0.93849325, 0.79216932,
       0.52001081, 0.8482931 , 0.55185897, 0.55107995, 0.54311791,
       0.63788335, 0.53554538, 0.65837271, 0.81226917, 0.82362796,
       0.57875233, 0.87780418, 0.82401747, 0.67769354, 0.68526607,
       0.56700402, 0.75235913, 0.61817301, 0.79556607, 0.70575543,
       0.7447866 , 0.55564523, 0.88615573, 0.58632485, 0.70915218,
       0.93092072, 0.55982101, 0.65458644, 0.82741422, 0.93470698,
       0.56739353, 0.92596593, 0.8198417 , 0.80091038, 0.84673505,
       0.77206947, 0.55525572, 0.60603519, 0.55603474, 0.91800389,
       0.73381732, 0.93431747, 0.74439709, 0.566225  , 0.51243829,
       0.56739353, 0.63827286, 0.61060048, 0.6064247 , 0.48894168,
       0.64924214, 0.80352811, 0.84712456, 0.6579832 , 0.72925203,
       0.58710387, 0.80809339, 0.72624479, 0.63788335, 0.55943

In [39]:
y_pred_train_losso = lasso_reg.predict(feature_admit_train)
y_pred_train_losso

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but Lasso was fitted without feature names
  warnings.warn(


array([0.77206947, 0.73225927, 0.5946764 , 0.70119014, 0.64963165,
       0.6981829 , 0.7447866 , 0.79595558, 0.6697315 , 0.65380742,
       0.69061037, 0.90586607, 0.80391762, 0.95742457, 0.53593489,
       0.73643505, 0.66594524, 0.84712456, 0.49874243, 0.6932281 ,
       0.67808305, 0.86605588, 0.72128999, 0.773238  , 0.73721407,
       0.69662486, 0.70196916, 0.90965234, 0.79556607, 0.52418659,
       0.78955158, 0.76032116, 0.76032116, 0.54011067, 0.83197951,
       0.54350742, 0.7913903 , 0.92179015, 0.73721407, 0.67429678,
       0.83120049, 0.62574553, 0.80013135, 0.58331761, 0.89868306,
       0.67769354, 0.90586607, 0.80352811, 0.67390727, 0.6814798 ,
       0.85887287, 0.56282825, 0.77624524, 0.72507626, 0.63788335,
       0.58632485, 0.77624524, 0.79216932, 0.57535557, 0.6348761 ,
       0.63331806, 0.79595558, 0.70196916, 0.63905188, 0.72128999,
       0.66215897, 0.77245898, 0.63070033, 0.72585528, 0.87062117,
       0.58214908, 0.65002116, 0.61700447, 0.52758334, 0.66973

In [35]:
### Evaluasi
# R2
# MAE
# RMSE
# MAPE

In [38]:
from sklearn.metrics import r2_score
print('R2 for testing data is {}'.format(r2_score(y_pred_losso, target_admit_test)*100))

R2 for testing data is 47.998201411278174


In [52]:
from sklearn.metrics import r2_score
print('R2 for testing data is {}'.format(r2_score(y_pred_ridge, target_admit_test)*100))

R2 for testing data is 79.64858319485295


In [40]:
print('R2 for training data is {}'.format(r2_score(y_pred_train_losso, y_admit_train)*100))

R2 for training data is 48.06264860330255


In [41]:
# underfitting under < 70%

In [42]:
from sklearn.metrics import mean_absolute_error

In [44]:
print('MAE for testing data is {}'.format(mean_absolute_error(y_pred_losso, target_admit_test)))

MAE for testing data is 0.06442838028075064


In [51]:
print('MAE for testing data is {}'.format(mean_absolute_error(y_pred_ridge, target_admit_test)))

MAE for testing data is 0.04273869040502614


In [45]:
print('MAE for training data is {}'.format(mean_absolute_error(y_pred_train_losso, y_admit_train)))

MAE for training data is 0.05873529037628709


In [46]:
# artinya ada error sekitar +-0.06 jika prediksi maka hasil pred ada error sekitar +-0.06

In [47]:
# data penjulan mobil MAE 500rb kecil
# data penjualan motor MAE 500rb besar

In [48]:
admit[['admit_prob']].describe()

,admit_prob
count,500.00000
mean,0.72174
std,0.14114
min,0.34000
25%,0.63000
50%,0.72000
75%,0.82000
max,0.97000


In [49]:
# penjualan_mobil[['price']].describe()
#rata mobil 500jt -> 500k

# penjualan_motor[['price']].describe()
#rata motir 30jt -> 500k

In [50]:
from sklearn.metrics import mean_squared_error

print('RMSE for testing data is {}'.format(np.sqrt(mean_squared_error(y_pred_losso, target_admit_test))))

RMSE for testing data is 0.08613079707937005


In [53]:
# MAE = RMSE
# RSME > MAE -> ada outluer prediksi

In [54]:
# load data
traffic = pd.read_csv('/content/drive/MyDrive/Bimbing/Regularized Regression in Python/traffic_volume.csv')
traffic.head()

,temp,clouds_all,hour,is_weekend,traffic_volume
0,288.28,40,9,0,5545
1,289.36,75,10,0,4516
2,289.58,90,11,0,4767
3,290.13,90,12,0,5026
4,291.14,75,13,0,4918


In [ ]:
# 100 data
# 20 test -> tidak terlibat dalam model -> real testing ->

# 20 val ->
# 60 train

In [56]:
# split train test
from sklearn.model_selection import train_test_split

feature = traffic.drop(columns='traffic_volume')
target = traffic[['traffic_volume']]

feature_traffic_pretrain, feature_traffic_test, target_traffic_pretrain, target_traffic_test = train_test_split(feature, target, test_size=0.20, random_state=42)

feature_traffic_train, feature_traffic_validation, target_traffic_train, target_traffic_validation = train_test_split(feature_traffic_pretrain, target_traffic_pretrain, test_size=0.20, random_state=42)

In [57]:
# calulcate vif scores
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif
from statsmodels.tools.tools import add_constant

X = add_constant(feature_traffic_train)

vif_df = pd.DataFrame([vif(X.values, i)
               for i in range(X.shape[1])],
              index=X.columns).reset_index()
vif_df.columns = ['feature','vif_score']
vif_df = vif_df.loc[vif_df.feature!='const']
vif_df

,feature,vif_score
1,temp,1.050419
2,clouds_all,1.037852
3,hour,1.013055
4,is_weekend,1.000949


In [58]:
from sklearn.linear_model import Lasso

# train the model
X_traffic_train = feature_traffic_train.to_numpy()
y_traffic_train = target_traffic_train.to_numpy()
y_traffic_train = y_traffic_train.reshape(len(y_traffic_train),)

# define the model
lasso_reg_pointzeroone = Lasso(alpha=0.01, random_state=42)
lasso_reg_pointone = Lasso(alpha=0.1, random_state=42)
lasso_reg_one = Lasso(alpha=1, random_state=42)
lasso_reg_ten = Lasso(alpha=10, random_state=42)

# fit the model (training)
lasso_reg_pointzeroone.fit(X_traffic_train, y_traffic_train)
lasso_reg_pointone.fit(X_traffic_train, y_traffic_train)
lasso_reg_one.fit(X_traffic_train, y_traffic_train)
lasso_reg_ten.fit(X_traffic_train, y_traffic_train)

Lasso(alpha=10, random_state=42)

In [59]:
from sklearn.metrics import mean_squared_error

X_traffic_validation = feature_traffic_validation.to_numpy()
y_traffic_validation = target_traffic_validation.to_numpy()
y_traffic_validation = y_traffic_validation.reshape(len(y_traffic_validation),)

alphas = [0.01, 0.1, 1., 10]
models = [lasso_reg_pointzeroone,
          lasso_reg_pointone,
          lasso_reg_one,
          lasso_reg_ten]

for model, alpha in zip(models, alphas):
    y_predict_validation = model.predict(X_traffic_validation)
    rmse = np.sqrt(mean_squared_error(y_traffic_validation,y_predict_validation))
    print(f'RMSE of Lasso regression model with alpha = {alpha} is {rmse}')

RMSE of Lasso regression model with alpha = 0.01 is 1758.7557046935883
RMSE of Lasso regression model with alpha = 0.1 is 1758.74786966802
RMSE of Lasso regression model with alpha = 1.0 is 1758.669967940547
RMSE of Lasso regression model with alpha = 10 is 1758.010309344725
